/* Parcours métier FASTE : devis interne, coûts prévus et planning partagé. */
'use strict';
const PlanningUI=(()=>{
 const P=FastePlanning,F=FasteFinance;
 let data={plans:[],members:[],bookings:[]},ready=false,error='',editing=null,busy=false;
 const categories=[['supplier','Prestataires'],['rental','Location matériel'],['transport','Transport'],['logistics','Logistique / hébergement'],['staff','Personnel facturé / coût salarial prévu'],['other','Autre']];
 const models=[['undecided','À définir'],['global','FASTE facture l’offre globale'],['direct','Client règle directement les autres prestataires'],['mixed','Mixte : certains prestataires via FASTE']];
 const pct=n=>n==null?'—':new Intl.NumberFormat('fr-FR',{maximumFractionDigits:1}).format(n)+' %';
 const button=(text,action,id='',cls='mini-btn')=>`<button type="button" class="${cls}" data-planning-action="${action}" data-id="${esc(id)}">${text}</button>`;
 async function all(table){const rows=[];for(let offset=0;;offset+=500){const r=await db.from(table).select('*').order(table==='event_quote_plans'?'quote_id':'id').range(offset,offset+499);if(r.error)throw r.error;rows.push(...r.data);if(r.data.length<500)return rows;}}
 async function load(){try{[data.plans,data.members,data.bookings]=await Promise.all(['event_quote_plans','event_team_members','event_resource_bookings'].map(all));ready=true;error='';}catch(e){ready=false;error=e.message;}}
 function labelFields(box){box.querySelectorAll('.field').forEach((row,i)=>{const label=row.querySelector('label'),control=row.querySelector('input,select,textarea');if(label&&control){control.id=box.id+'-field-'+i;label.htmlFor=control.id;}});}
 const plan=id=>data.plans.find(p=>p.quote_id===id)||null;
 function quoteForm(doc){
  const box=$('#quotePlanPanel');if(!box)return;
  box.hidden=doc.type==='facture';if(box.hidden){box.innerHTML='';return;}
  if(!ready){box.innerHTML=`<p class="finance-notice">Budget interne indisponible : ${esc(error||'chargement en cours')}. Actualisez avant d’enregistrer un devis.</p>`;return;}
  const p=plan(doc.id)||{};
  box.innerHTML=`<details class="explain-details" open><summary>Budget client et marge prévue · interne à FASTE</summary><p class="list-scope">Ces informations ne sont pas imprimées sur le devis client. Le devis contient uniquement les prestations facturées par FASTE.</p><div class="planning-fields">${field('Budget global du client TTC (€)','planning_client_budget_ttc',p.client_budget_ttc??'',{type:'number',min:0,step:'.01'})}${field('Qui facture les prestations ?','planning_billing_model',p.billing_model||'undecided',{choices:models})}${field('Autres prestataires payés directement par le client : total TTC (€)','planning_external_client_ttc',p.external_client_ttc||0,{type:'number',min:0,step:'.01',full:true})}</div><div id="quoteBudgetPreview" class="list-scope"></div><div class="panel-head"><div><h3>Ce que la prestation coûtera à FASTE</h3><p>Prestataires, location, transport et autres coûts prévus. Montant HT si la TVA sera récupérable, sinon coût TTC. Les paiements directs du client restent dans le total séparé ci-dessus.</p></div>${button('+ Coût prévu','add-cost','','btn ghost')}</div><div id="quoteCostLines"></div><label class="planning-check"><input type="checkbox" name="planning_costs_checked" ${p.costs_checked?'checked':''}> J’ai vérifié que tous les coûts prévus pour FASTE sont inclus, même s’ils sont nuls.</label><div id="quoteMarginPreview" class="event-financial-grid"></div><details class="explain-details"><summary>Estimer aussi notre temps de travail</summary><p class="list-scope">Heures-personnes : deux personnes pendant quatre heures = huit heures. Cette valorisation interne ne crée ni salaire ni charge comptable. Ne recomptez pas le personnel déjà inclus dans les coûts ci-dessus.</p><div class="planning-fields">${field('Préparation (heures-personnes)','planning_preparation_hours',p.preparation_hours||0,{type:'number',min:0,step:'.25'})}${field('Montage / installation (heures-personnes)','planning_setup_hours',p.setup_hours||0,{type:'number',min:0,step:'.25'})}${field('Prestation / exploitation (heures-personnes)','planning_operation_hours',p.operation_hours||0,{type:'number',min:0,step:'.25'})}${field('Démontage / retour (heures-personnes)','planning_teardown_hours',p.teardown_hours||0,{type:'number',min:0,step:'.25'})}${field('Valeur interne d’une heure (€)','planning_hourly_value',p.hourly_value||0,{type:'number',min:0,step:'.01'})}</div><p id="quoteTimePreview" class="list-scope"></p></details></details>`;
  labelFields(box);(p.costs||[]).forEach(addCost);previewQuote();
 }
 function addCost(cost={}){
  const row=document.createElement('div');row.className='quote-cost-row';row.innerHTML=`<label>Coût prévu<input class="cost-label" value="${esc(cost.label||'')}" placeholder="Ex. location de deux lyres" required></label><label>Catégorie<select class="cost-category">${categories.map(([v,l])=>`<option value="${v}" ${cost.category===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Montant (€)<input class="cost-amount" type="number" min="0" step=".01" value="${cost.amount??''}" required></label><button type="button" class="icon-btn" data-planning-action="remove-cost" aria-label="Retirer ce coût prévu">×</button>`;
  $('#quoteCostLines').appendChild(row);
 }
 function readPlan(){
  const box=$('#quotePlanPanel'), value=k=>box.querySelector(`[name="planning_${k}"]`)?.value;
  const p={billing_model:value('billing_model')||'undecided',client_budget_ttc:value('client_budget_ttc')===''?null:Number(value('client_budget_ttc')),external_client_ttc:Number(value('external_client_ttc')||0),costs_checked:box.querySelector('[name="planning_costs_checked"]')?.checked===true};
  for(const k of ['preparation_hours','setup_hours','operation_hours','teardown_hours','hourly_value'])p[k]=Number(value(k)||0);
  p.costs=$$('.quote-cost-row',box).map(r=>({label:$('.cost-label',r).value.trim(),category:$('.cost-category',r).value,amount:Number($('.cost-amount',r).value||0)}));
  return p;
 }
 function previewQuote(){
  if(!ready||!$('#quoteMarginPreview'))return;
  const p=readPlan(),q=documentTotals(),r=P.forecast(p,{total_ht:q.ht,total_ttc:q.ttc});
  const model=models.find(x=>x[0]===p.billing_model)?.[1]||'À définir';
  $('#quoteBudgetPreview').textContent=`${model} · Devis FASTE : ${euro(q.ttc)} TTC + autres prestataires réglés directement par le client : ${euro(p.external_client_ttc)} TTC = ${euro(r.totalClient)} de budget utilisé.${r.budget==null?' Budget global non renseigné.':r.gap<0?' Dépassement du budget : '+euro(-r.gap)+'.':' Budget restant : '+euro(r.gap)+'.'}${p.billing_model==='global'&&p.external_client_ttc>0?' Des paiements directs sont prévus : vérifiez si le modèle Mixte convient.':''}`;
  $('#quoteBudgetPreview').classList.toggle('negative',r.gap<0);
  $('#quoteMarginPreview').innerHTML=`<article class="kpi"><span>Coûts prévus FASTE</span><strong>${euro(r.costs)}</strong><small>${r.checked?'Coûts déclarés complets':'À compléter / vérifier'}</small></article><article class="kpi"><span>Marge prévue avant frais généraux</span><strong class="${r.margin<0?'negative':''}">${euro(r.margin)}</strong><small>${pct(r.rate)} du devis HT · ${r.checked?'estimation':'provisoire, coûts à vérifier'}</small></article><article class="kpi"><span>Devis FASTE HT</span><strong>${euro(r.revenue)}</strong><small>Le budget global du client n’est pas votre chiffre d’affaires.</small></article>`;
  $('#quoteTimePreview').textContent=`${r.hours} heures-personnes × ${euro(p.hourly_value)} = ${euro(r.timeValue)} de travail valorisé. Marge après cette valorisation : ${euro(r.afterTime)}.${r.hours>0&&!p.hourly_value?' La valeur horaire est à renseigner.':''} Avant frais généraux et impôt ; aucune écriture créée.`;
 }
 function eventPanel(id){
  const box=$('#eventPlanningPanel'),e=state.events.find(x=>x.id===id);if(!box||!e)return;
  if(!ready){$('#eventBudgetPanel').innerHTML='';box.innerHTML=`<p class="finance-notice">Planning indisponible : ${esc(error)}. Actualisez.</p>`;return;}
  const p=plan(e.source_quote_id),q=e.quote||state.documents.find(d=>d.id===e.source_quote_id),actual=typeof FinanceUI!=='undefined'?FinanceUI.eventSummary(id):null;
  let commercial=p?(()=>{const r=P.forecast(p,q);return `<p class="list-scope"><strong>${esc(models.find(x=>x[0]===p.billing_model)?.[1]||'À définir')}</strong> · Budget client ${r.budget==null?'non renseigné':euro(r.budget)+' TTC'} · Devis FASTE ${euro(q?.total_ttc)} TTC · Autres prestataires payés par le client ${euro(p.external_client_ttc)} TTC.${r.gap<0?' Dépassement : '+euro(-r.gap)+'.':''}</p><div class="table-wrap"><table><thead><tr><th>Comparaison avant frais généraux et impôt</th><th>Prévu au devis</th><th>Réel saisi à ce jour</th></tr></thead><tbody><tr><td>Recettes FASTE HT</td><td>${euro(r.revenue)}</td><td>${actual?euro(actual.billed):'À charger'}</td></tr><tr><td>Coûts directs FASTE</td><td>${euro(r.costs)}</td><td>${actual?euro(actual.costs):'À charger'}</td></tr><tr><td>Marge directe</td><td>${euro(r.margin)} · ${pct(r.rate)}</td><td>${actual?euro(actual.margin)+' · '+pct(actual.rate):'À charger'}</td></tr></tbody></table></div><p class="list-scope">${r.checked?'Prévision déclarée complète.':'Coûts prévus encore à vérifier.'} Écart de coûts : ${actual?euro(F.money(F.cents(actual.costs)-F.cents(r.costs))):'—'} (réel − prévu). Le réel reste partiel tant que toutes les factures et dépenses ne sont pas saisies. Travail valorisé prévu : ${euro(r.timeValue)} pour ${r.hours} heures-personnes ; séparé du résultat comptable. La prévision est modifiable dans le devis.</p>`;})():'<p class="list-scope">Budget et coûts prévus non renseignés. Ouvrez le devis pour les compléter.</p>';
  const bookings=data.bookings.filter(b=>b.event_id===id&&b.status!=='cancelled');
  $('#eventBudgetPanel').innerHTML=`<details class="panel explain-details" open><summary>Budget client et comparaison prévu / réel</summary>${commercial}${q?`<button type="button" class="btn ghost" data-edit-document="${esc(q.id)}">Ouvrir le devis et ses coûts prévus</button>`:''}</details>`;
  box.innerHTML=`<details class="panel explain-details" open><summary>Matériel, équipe et prestataires (${bookings.length})</summary><p class="list-scope">Réservez du montage au retour. Horaires en France. Une réservation ne crée aucun achat ni paiement. Si la date de l’événement change, vérifiez aussi les dates des réservations.</p><div class="workflow-actions">${button('+ Réserver une ressource','new-booking',id,'btn primary')}<button type="button" class="btn ghost" data-go="planning">Voir toutes les disponibilités</button></div><div class="dossier-lines">${bookings.map(bookingLine).join('')||'<p>Aucune ressource affectée à cet événement.</p>'}</div></details>`;
 }
 function resourceName(b){return b.kind==='material'?state.materials.find(m=>m.id===b.material_id)?.nom||'Matériel':b.kind==='team'?data.members.find(m=>m.id===b.member_id)?.name||'Équipe':state.contacts.find(c=>c.id===b.contact_id)?.name||'Prestataire';}
 const range=b=>P.parisInput(b.starts_at).replace('T',' à ')+' → '+P.parisInput(b.ends_at).replace('T',' à ');
 function conflictText(b){const c=P.conflicts(b,data.bookings,state.materials);if(!c)return '';const names=[...new Set(c.bookings.map(x=>state.events.find(e=>e.id===x.event_id)?.title||'autre réservation'))].join(', ');return c.type==='supplier'?`Prestataire aussi prévu sur ${names} : vérifier qu’il dispose de plusieurs équipes.`:`Conflit : ${c.peak} prévu(s) simultanément pour ${c.capacity} disponible(s). ${names}`;}
 function bookingLine(b){const warning=conflictText(b);return `<div><span><strong>${esc(resourceName(b))}${b.kind==='material'?' × '+b.quantity:''}</strong> · ${esc(b.label)}<span class="cell-sub">${esc(range(b))} · ${b.status==='confirmed'?'Confirmé':'À confirmer'}${b.kind==='supplier'?' · payé par '+(b.paid_by==='client'?'le client':'FASTE'):''}</span>${warning?`<span class="cell-sub negative">${esc(warning)}</span>`:''}</span>${button('Modifier','edit-booking',b.id)}${button('Annuler','cancel-booking',b.id)}</div>`;}
 function render(){
  const box=$('#resourceBoard');if(!box)return;
  if(ready && $('#documentModal').classList.contains('open') && $('#documentForm [name="type"]')?.value==='devis' && !$('#quotePlanPanel [name="planning_billing_model"]')) quoteForm(state.documents.find(d=>d.id===state.editingDocument)||readDocumentHeader());
  $('#planningError').hidden=ready;$('#planningError').textContent=ready?'':'Planning indisponible : '+error;
  if(!ready){box.innerHTML='';return;}
  const from=$('#planningFrom').value,to=$('#planningTo').value,kind=$('#planningKind').value,q=$('#planningSearch').value.toLowerCase();
  const rows=data.bookings.filter(b=>b.status!=='cancelled'&&(!from||P.parisInput(b.ends_at).slice(0,10)>=from)&&(!to||P.parisInput(b.starts_at).slice(0,10)<=to)&&(kind==='all'||b.kind===kind)&&`${resourceName(b)} ${state.events.find(e=>e.id===b.event_id)?.title||''} ${b.label}`.toLowerCase().includes(q)).sort((a,b)=>a.starts_at.localeCompare(b.starts_at));
  const warnings=rows.filter(b=>conflictText(b));
  $('#planningCount').textContent=`${rows.length} réservation(s) · ${warnings.length} alerte(s) à vérifier dans cette sélection.`;
  box.innerHTML=rows.map(b=>`<article class="panel"><div class="panel-head"><div><h3>${esc(state.events.find(e=>e.id===b.event_id)?.title||'Événement')}</h3></div><button class="text-link" data-edit-event="${esc(b.event_id)}">Ouvrir le dossier →</button></div><div class="dossier-lines">${bookingLine(b)}</div></article>`).join('')||'<div class="empty-state panel">Aucune réservation dans cette sélection. Ouvrez un événement pour affecter le matériel, l’équipe ou un prestataire.</div>';
  $('#planningTeamList').innerHTML=data.members.filter(m=>m.active).map(m=>`<span class="badge">${esc(m.name)}</span>`).join(' ');
  if(state.editingEvent&&$('#eventModal').classList.contains('open'))eventPanel(state.editingEvent);
 }
 function fillResources(kind,id){const select=$('#planningForm [name="resource_id"]');const list=kind==='material'?state.materials.map(m=>[m.id,m.nom+' · stock '+m.quantite]):kind==='team'?data.members.filter(m=>m.active).map(m=>[m.id,m.name]):state.contacts.filter(c=>c.type==='prestataire').map(c=>[c.id,c.name]);select.innerHTML='<option value="">Choisir…</option>'+list.map(([v,l])=>`<option value="${esc(v)}">${esc(l)}</option>`).join('');select.value=id||'';$('#planningForm [name="quantity"]').closest('.field').hidden=kind!=='material';}
 function bookingForm(eventId,id=null){
  if(!ready)return;const b=data.bookings.find(x=>x.id===id)||{},e=state.events.find(x=>x.id===(b.event_id||eventId));if(!e)return;
  editing={type:'booking',id,eventId:e.id};const date=e.event_date||today(),start=P.parisInput(b.starts_at)||date+'T'+(e.setup_time?.slice(0,5)||'09:00');
  let end=P.parisInput(b.ends_at)||date+'T'+(e.teardown_time?.slice(0,5)||'23:59');if(!b.ends_at&&end<=start){const next=new Date(date+'T12:00:00Z');next.setUTCDate(next.getUTCDate()+1);end=next.toISOString().slice(0,10)+end.slice(10);}
  $('#planningModalTitle').textContent='Ressource · '+e.title;
  $('#planningForm').innerHTML=[field('Type','kind',b.kind||'material',{choices:[['material','Matériel FASTE'],['team','Équipe'],['supplier','Prestataire']]}),field('Ressource','resource_id','',{choices:[],required:true}),field('Quantité','quantity',b.quantity||1,{type:'number',min:1,step:1,required:true}),field('Mission / utilisation','label',b.label||'',{required:true,placeholder:'DJ, montage, sonorisation, traiteur…'}),field('Disponible à partir de','starts_at',start,{type:'datetime-local',required:true}),field('Retour / fin de mission','ends_at',end,{type:'datetime-local',required:true}),field('Confirmation','status',b.status||'tentative',{choices:[['tentative','À confirmer'],['confirmed','Confirmé']]}),field('Qui règle le prestataire ?','paid_by',b.paid_by||'faste',{choices:[['faste','FASTE'],['client','Le client directement']]}),field('Note','notes',b.notes||'',{rows:2,full:true})].join('');
  labelFields($('#planningForm'));fillResources(b.kind||'material',b.material_id||b.member_id||b.contact_id);$('#planningForm [name="paid_by"]').closest('.field').hidden=(b.kind||'material')!=='supplier';$('#planningFormError').textContent='';$('#planningSaveBtn').disabled=false;openModal('planningModal');bookingPreview();
 }
 function readBooking(){const v=Object.fromEntries(new FormData($('#planningForm')));const starts=P.parisUTC(v.starts_at),ends=P.parisUTC(v.ends_at);if(ends<=starts)throw new Error('La fin doit être après le début, y compris pour une prestation après minuit.');return {event_id:editing.eventId,kind:v.kind,material_id:v.kind==='material'?v.resource_id:null,member_id:v.kind==='team'?v.resource_id:null,contact_id:v.kind==='supplier'?v.resource_id:null,quantity:v.kind==='material'?Number(v.quantity):1,label:v.label.trim(),starts_at:starts,ends_at:ends,status:v.status,paid_by:v.kind==='supplier'?v.paid_by:'faste',notes:v.notes||null};}
 function bookingPreview(){try{const b={...readBooking(),id:editing.id};$('#planningFormError').textContent=conflictText(b)||'Aucun conflit détecté dans les réservations saisies. Les confirmations de matériel et d’équipe sont aussi contrôlées à l’enregistrement.';}catch(e){$('#planningFormError').textContent=e.message;}}
 function memberForm(){editing={type:'member'};$('#planningModalTitle').textContent='Ajouter un équipier';$('#planningForm').innerHTML=field('Nom de l’équipier','name','',{required:true,full:true});labelFields($('#planningForm'));$('#planningFormError').textContent='Un nom unique pour éviter les doubles affectations. Aucun salaire n’est calculé.';$('#planningSaveBtn').disabled=false;openModal('planningModal');}
 async function save(e){e.preventDefault();if(busy||!ready)return;busy=true;$('#planningSaveBtn').disabled=true;try{let r;if(editing.type==='member'){const v=Object.fromEntries(new FormData(e.currentTarget));r=await db.from('event_team_members').insert({name:v.name.trim()});}else{const payload=readBooking();r=editing.id?await db.from('event_resource_bookings').update(payload).eq('id',editing.id).select('id').single():await db.from('event_resource_bookings').insert(payload).select('id').single();}if(r.error)throw r.error;closeModal('planningModal');toast('Planning enregistré et partagé.');await loadData({quiet:true});}catch(error){$('#planningFormError').textContent=error.message;}finally{busy=false;$('#planningSaveBtn').disabled=false;}}
 async function actions(e){const b=e.target.closest('[data-planning-action]');if(!b||!ready||busy)return;switch(b.dataset.planningAction){case 'add-cost':addCost();$('#quotePlanPanel [name="planning_costs_checked"]').checked=false;previewQuote();break;case 'remove-cost':b.closest('.quote-cost-row').remove();$('#quotePlanPanel [name="planning_costs_checked"]').checked=false;previewQuote();break;case 'new-booking':bookingForm(b.dataset.id);break;case 'edit-booking':bookingForm(null,b.dataset.id);break;case 'new-member':memberForm();break;case 'cancel-booking':if(confirm('Annuler cette réservation ? Elle restera conservée, sans bloquer la ressource.')){busy=true;try{const r=await db.from('event_resource_bookings').update({status:'cancelled'}).eq('id',b.dataset.id).select('id').single();if(r.error)throw r.error;await loadData({quiet:true});}catch(err){toast(err.message,true);}finally{busy=false;}}break;}}
 function bind(){document.addEventListener('click',actions);$('#quotePlanPanel').addEventListener('input',e=>{if(e.target.closest('.quote-cost-row'))$('#quotePlanPanel [name="planning_costs_checked"]').checked=false;previewQuote();});$('#quotePlanPanel').addEventListener('change',previewQuote);$('#planningForm').addEventListener('submit',save);$('#planningForm').addEventListener('input',()=>{if(editing?.type==='booking')bookingPreview();});$('#planningForm').addEventListener('change',e=>{if(editing?.type!=='booking')return;if(e.target.name==='kind'){fillResources(e.target.value);$('#planningForm [name="paid_by"]').closest('.field').hidden=e.target.value!=='supplier';}bookingPreview();});['planningFrom','planningTo','planningKind'].forEach(id=>$('#'+id).addEventListener('change',render));$('#planningSearch').addEventListener('input',render);$('#resetPlanningFilters').addEventListener('click',()=>{['planningFrom','planningTo','planningSearch'].forEach(id=>$('#'+id).value='');$('#planningKind').value='all';render();});}
 return {load,render,bind,quoteForm,readPlan,previewQuote,eventPanel,isReady:()=>ready,plans:()=>data.plans,bookings:()=>data.bookings};
})();
