'use strict';
const { test } = require('node:test');
const assert = require('node:assert/strict');
const E = require('../finance-export.js');
function fixture() { return { documents:[{id:'i',type:'facture',number:'FAC-1',document_date:'2026-10-01',event_date:'2026-09-30',total_ht:1000,total_vat:200,total_ttc:1200,finance_initial_paid:0,contact:{name:'Client'}}],expenses:[{id:'e',supplier:'Loueur',reference:'LOC-1',document_date:'2026-10-01',due_date:'2026-10-10',category:'Location',kind:'charge',amount_ht:100,amount_vat:20,deduction_status:'yes',deductible_vat:20}],payments:[{id:'p',document_id:'i',amount:600,payer:'bank',payment_date:'2026-10-02',reference:'VIR-1'}],credits:[{id:'c',document_id:'i',number:'AV-1',amount_ht:100,amount_vat:20,document_date:'2026-10-03',reason:'Réduction'}],flows:[],events:[],settings:{balance_date:'2026-09-30',balance_amount:0},attachments:[{id:'a',expense_id:'e',filename:'facture.pdf'}],lines:[] }; }
const objects = rows => rows.slice(1).map(r => Object.fromEntries(rows[0].map((h,i) => [h,r[i]])));
test('tableau unique : facture et encaissement séparés, avoir négatif', () => { const rows=objects(E.journal(fixture(),'2026-10-01','2026-10-31')); const invoice=rows.find(r => r.Type==='Facture client'), payment=rows.find(r => r.Type==='Encaissement client'), credit=rows.find(r => r.Type==='Avoir client'); assert.equal(invoice['HT (€)'],1000); assert.equal(invoice['Entrée banque (€)'],null); assert.equal(payment['HT (€)'],null); assert.equal(payment['Entrée banque (€)'],600); assert.equal(credit['TTC (€)'],-120); assert.equal(invoice['Reste à fin période (€)'],480); });
test('justificatif relié à sa ligne et frais personnels séparés de la banque', () => { const d=fixture(); d.payments.push({id:'p2',expense_id:'e',amount:120,payer:'Maxime',payment_date:'2026-10-03',reference:'CB'}); const rows=objects(E.journal(d,'2026-10-01','2026-10-31')), expense=rows.find(r => r.Type==='Dépense fournisseur'), personal=rows.find(r => r.Type==='Frais avancés associé'); assert.equal(expense['Justificatifs / PDF'],'justificatifs/a-facture.pdf'); assert.equal(personal['Frais avancés associé (€)'],120); assert.equal(personal['Sortie banque (€)'],null); assert.equal(personal['Pièce liée'],'LOC-1'); });
test('pièces hors période gardées sans gonfler la facturation exportée', () => { const d=fixture(); d.documents[0].document_date='2026-09-01'; const rows=objects(E.journal(d,'2026-10-01','2026-10-31')), linked=rows.find(r => r.Type==='Pièce liée hors période'); assert.equal(linked['HT (€)'],null); assert.equal(linked['TTC (€)'],null); assert.match(linked.Notes,/1200/); });
test('annulations et prévisions ne sont pas des mouvements réalisés', () => { const d=fixture(); d.payments[0].cancelled=true; d.credits[0].cancelled=true; d.flows=[{id:'f',label:'Impôt',flow_date:'2026-10-15',amount:-50,realized:false}]; const rows=objects(E.journal(d,'2026-10-01','2026-10-31')); assert.equal(rows.find(r => r.Type==='Encaissement client')['Entrée banque (€)'],0); assert.equal(rows.find(r => r.Type==='Avoir client')['TTC (€)'],0); assert.equal(rows.find(r => r.Type==='Autre mouvement')['Sortie banque (€)'],null); });
test('devis non facturé et marges restent informatifs dans le même tableau', () => { const d=fixture(); d.documents.push({id:'q',type:'devis',status:'accepted',number:'DEV-1',document_date:'2026-10-01',total_ttc:1800}); const rows=objects(E.journal(d,'2026-10-01','2026-10-31')), quote=rows.find(r => r.Type==='Devis à facturer'), margin=rows.find(r => r.Type==='Synthèse marge'); assert.equal(quote['TTC (€)'],null); assert.match(quote.Notes,/1800/); assert.equal(margin['Indicateur (€)'],900); assert.equal(margin['Marge (%)'],100); });
test('un seul onglet Excel avec toutes les lignes du journal', async () => { const ExcelJS=require('exceljs'), rows=E.journal(fixture(),'2026-10-01','2026-10-31'), wb=new ExcelJS.Workbook(); const s=wb.addWorksheet('Journal comptable'); s.addTable({name:'JournalFASTE',ref:'A1',headerRow:true,columns:rows[0].map(name => ({name,filterButton:true})),rows:rows.slice(1).map(r => r.map(x => x??''))}); const loaded=new ExcelJS.Workbook(); await loaded.xlsx.load(await wb.xlsx.writeBuffer()); assert.equal(loaded.worksheets.length,1); assert.equal(loaded.worksheets[0].rowCount,rows.length); assert.equal(loaded.worksheets[0].getCell('B2').value,'Dépense fournisseur'); });
test('export unique conserve ajustements et résultats avant/après IS avec leurs pièces',()=>{const d=fixture();d.adjustments=[{id:'a',document_date:'2026-10-01',category:'depreciation',amount:-100,label:'Dotation',reference:'AM-1'}];d.attachments.push({id:'ja',adjustment_id:'a',filename:'calcul.pdf'});const rows=objects(E.journal(d,'2026-10-01','2026-10-31'));assert.equal(rows.find(r=>r.Type==='Ajustement résultat')['Justificatifs / PDF'],'justificatifs/ja-calcul.pdf');assert.equal(rows.find(r=>r['Libellé / détail']==='Résultat avant IS')['Indicateur (€)'],700);assert.equal(rows.find(r=>r['Libellé / détail']==='Résultat après IS estimé')['Indicateur (€)'],525);});
test('budget global et marge prévue restent informatifs sans gonfler factures ou banque',()=>{const d=fixture();d.documents.push({id:'q',type:'devis',status:'accepted',number:'DEV-30K',document_date:'2026-10-01',total_ht:10000,total_ttc:12000});d.plans=[{quote_id:'q',billing_model:'mixed',client_budget_ttc:30000,external_client_ttc:18000,costs:[{label:'Location',category:'rental',amount:2000}],costs_checked:true}];const rows=objects(E.journal(d,'2026-10-01','2026-10-31')),plan=rows.find(r=>r.Type==='Budget et marge prévus');assert.equal(plan['Indicateur (€)'],8000);assert.equal(plan['Marge (%)'],80);for(const col of ['HT (€)','TTC (€)','Entrée banque (€)','Sortie banque (€)'])assert.equal(plan[col],null);assert.match(plan.Notes,/30000/);assert.equal(rows.filter(r=>r.Type==='Facture client').reduce((n,r)=>n+r['HT (€)'],0),1000);assert.equal(rows.filter(r=>r.Type==='Encaissement client').reduce((n,r)=>n+r['Entrée banque (€)'],0),600);});
